  name: Sub wf 1
  run-name: Sub wf depth ${{ inputs.depth }}

  on:
    pull_request:
    push:
      branches:
        - main
    workflow_call:
      depth:
        description: WF depth
        required: false
        default: '-1'


  jobs:
    main:
      name: Main
      runs-on: ubuntu-latest
      steps:
        - name: Depth
          shell: bash
          run: |
            echo "Depth is ${{ inputs.depth }}"
    sub:
      name: Calling sub workflow
      needs:
        - main
      uses: ./.github/workflows/sub-workflow-1.yaml
      with:
        depth: ${{ needs.main.outputs.depth }}
